// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArOywVk1FhMIzkLe4uZFF7iZFKbpFwTfo',
    appId: '1:479063971697:web:590d5e45f4ece8325c88d0',
    messagingSenderId: '479063971697',
    projectId: 'vibehello-5ec29',
    authDomain: 'vibehello-5ec29.firebaseapp.com',
    storageBucket: 'vibehello-5ec29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKI-qYcUC-HuqYDS3Be1u8Hy1T3I1w4V0',
    appId: '1:479063971697:android:d76b560a871211295c88d0',
    messagingSenderId: '479063971697',
    projectId: 'vibehello-5ec29',
    storageBucket: 'vibehello-5ec29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSL5JAWOV8OWN85PWTkIFbmeowpdWVWA',
    appId: '1:479063971697:ios:78548228344803a95c88d0',
    messagingSenderId: '479063971697',
    projectId: 'vibehello-5ec29',
    storageBucket: 'vibehello-5ec29.firebasestorage.app',
    iosBundleId: 'com.example.vibehello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSL5JAWOV8OWN85PWTkIFbmeowpdWVWA',
    appId: '1:479063971697:ios:78548228344803a95c88d0',
    messagingSenderId: '479063971697',
    projectId: 'vibehello-5ec29',
    storageBucket: 'vibehello-5ec29.firebasestorage.app',
    iosBundleId: 'com.example.vibehello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArOywVk1FhMIzkLe4uZFF7iZFKbpFwTfo',
    appId: '1:479063971697:web:43fc776509783bb45c88d0',
    messagingSenderId: '479063971697',
    projectId: 'vibehello-5ec29',
    authDomain: 'vibehello-5ec29.firebaseapp.com',
    storageBucket: 'vibehello-5ec29.firebasestorage.app',
  );
}
